#!/usr/bin/env sh

#
# WARN: for this to work you must configure sudo such that
# it will be able to run the command without password
# +) Disable System Integrity Protection on macOS
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp, stack, or float
yabai -m config \
  focus_follows_mouse off \
  mouse_follows_focus off \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.90 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  layout bsp \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  top_padding 8 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 8

# Disable specific apps
yabai -m rule --add \
  app="KakaoTalk|System Settings|Raycast|Telegram|TickTick|Spotify|CleanMyMac|CleanShot X|Finder|1Password|TablePlus|Exosphere" \
  manage=off

# window rules
yabai -m rule --add \
  app="Channel Talk" \
  space=1
yabai -m rule --add \
  app="Slack" \
  space=1
yabai -m rule --add \
  app="Brave Browser" \
  space=3
yabai -m rule --add \
  app="Linear" \
  space=4
yabai -m rule --add \
  app="Notion" \
  space=5

# apply rule for current windows
yabai -m rule --apply
