#!/usr/bin/env sh

# Changing Window Focus

# change window focus within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

# change focus between external displays (left and right)
# alt - s : yabai -m display --focus west
# alt - g : yabai -m display --focus east

# rotate layout clockwise
shift + alt -r : yabai -m space --rotate 270

# flip along the y-axis
shift + alt - y : yabai -m space --mirror y-axis
# flip along the x-axis
shift + alt - x : yabai -m space --mirror x-axis

# toggle window float
# shift + alt - f : yabai -m window --toggle float --grid 4:4:1:1:2:2

# Modify Window Size

# maximize a window
ctrl + alt - return : yabai -m window --toggle zoom-fullscreen

# balance out tree of windows (resize to occupy same area)
# shift + alt - e : yabai -m space --balance

# swap windows
# ctrl + alt - j : yabai -m window --swap south
# ctrl + alt - k : yabai -m window --swap north
# ctrl + alt - h : yabai -m window --swap west
# ctrl + alt - l : yabai -m window --swap east

# move window and split
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - h : yabai -m window --warp west
shift + alt - l : yabai -m window --warp east

# move window to display left and right
# shift + alt - s : yabai -m window --display west; yabai -m display --focus west
# shift + alt - g : yabai -m window --display east; yabai -m display --focus east

# move window to prev and next space
# shift + alt - p : yabai -m window --space prev
# shift + alt - n : yabai -m window --space next

# move focus to display 1-7
# NOTE: System Settings → Desktop & Dock → Mission Control
# → disable "Automatically rearrange Spaces based on most recent use"
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 5 : yabai -m space --focus 6
alt - 5 : yabai -m space --focus 7
shift + cmd - h : yabai -m space --focus prev
shift + cmd - l : yabai -m space --focus next

# move window to space 1-7
shift + alt - 1 : yabai -m window --space 1
shift + alt - 2 : yabai -m window --space 2
shift + alt - 3 : yabai -m window --space 3
shift + alt - 4 : yabai -m window --space 4
shift + alt - 5 : yabai -m window --space 5
shift + alt - 6 : yabai -m window --space 6
shift + alt - 7 : yabai -m window --space 7

ctrl + alt - h : yabai -m window --resize left:-30:0
ctrl + alt - l : yabai -m window --resize right:30:0
# ctrl + alt - n : yabai -m window --resize bottom:0:20
# ctrl + alt - e : yabai -m window --resize top:0:-20
