# zmodload zsh/datetime
# zsh_start_time=$EPOCHREALTIME
#
# zsh_end_time=$EPOCHREALTIME
# zsh_load_time=$(echo "($zsh_end_time - $zsh_start_time) * 1000" | bc)
# echo "zsh startup time: ${zsh_load_time}ms"

# --- PATH ---
path=(
    /usr/local/bin $HOME/bin
    /opt/homebrew/bin # homebrew
    /opt/homebrew/opt/postgresql@17/bin # postgresql@17
    $HOME/.local/bin $HOME/go/bin # go
    $HOME/.local/share/bob/nvim-bin # bob-nvim
    $path
)

# --- DEFAULT ---
export EDITOR=nvim
export TERM=xterm-256color
export AWS_PROFILE=ch-dev

# --- oh-my-posh ---
eval "$(oh-my-posh init zsh --config $HOME/dotfiles/oh-my-posh.toml)"

# --- ANTIDOTE ---
source /opt/homebrew/opt/antidote/share/antidote/antidote.zsh # installed by brew
antidote load $HOME/dotfiles/zsh/zsh_plugins.txt

# --- MISE ---
export MISE_GLOBAL_CONFIG_FILE=$HOME/dotfiles/mise.toml
eval "$(mise activate zsh)"

(( $+commands[mise] )) && (( $+commands[terraform] )) && complete -o nospace -C $(mise which terraform) terraform

# --- fzf ---
[ -f /opt/homebrew/bin/fzf ] && source <(fzf --zsh)
alias f="cd \$(fd --type directory --hidden --exclude .git | fzf)"

# --- COMPLETION ---
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit

# --- ZSH FILES ---
source $HOME/dotfiles/zsh/alias.zsh
source $HOME/dotfiles/zsh/secret.zsh


